// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bizomet.Data.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20220113135757_2022.00.00.01")]
	partial class _2022000001
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.1")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedName")
						.IsUnique()
						.HasDatabaseName("RoleNameIndex")
						.HasFilter("[NormalizedName] IS NOT NULL");

					b.ToTable("AspNetRoles", (string) null);

					b.HasData(
						new
						{
							Id = "1bfc52cb-7472-4a71-9ddb-17e5e32c329c",
							ConcurrencyStamp = "0fe07f18-58d7-4b7d-8319-a2abe8eb03fb",
							Name = "Administrator",
							NormalizedName = "ADMINISTRATOR"
						},
						new
						{
							Id = "d238b630-ef04-450c-a2f1-1a8346a59cbc",
							ConcurrencyStamp = "197a2f9b-347a-4649-b515-322cc8a3a045",
							Name = "Talent",
							NormalizedName = "TALENT"
						},
						new
						{
							Id = "330a8560-16ff-444f-a5b9-e01a62b4a5d3",
							ConcurrencyStamp = "78d34cd1-db9d-474a-a175-e775ece04ffb",
							Name = "Lifter",
							NormalizedName = "LIFTER"
						},
						new
						{
							Id = "55e06bd5-e542-436d-bea4-2afedf2c1b8f",
							ConcurrencyStamp = "6f9a2a13-c833-409d-81b6-8feb9bc51c5f",
							Name = "MediaAssistant",
							NormalizedName = "MEDIAASSISTANT"
						},
						new
						{
							Id = "6193612c-c669-4713-bf45-d97927724b55",
							ConcurrencyStamp = "d2c7894f-4063-4a93-8bc0-bf930592e6e0",
							Name = "Promoter",
							NormalizedName = "PROMOTER"
						});
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<int>("AccessFailedCount")
						.HasColumnType("int");

					b.Property<string>("AddressLine1")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("AddressLine2")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("City")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Country")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Email")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<bool>("EmailConfirmed")
						.HasColumnType("bit");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<bool>("LockoutEnabled")
						.HasColumnType("bit");

					b.Property<DateTimeOffset?>("LockoutEnd")
						.HasColumnType("datetimeoffset");

					b.Property<string>("NameTitle")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<string>("NormalizedEmail")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("PasswordHash")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PhoneNumber")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberBusiness")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberCell")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<bool>("PhoneNumberConfirmed")
						.HasColumnType("bit");

					b.Property<string>("PhoneNumberFax")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberHome")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PostalCode")
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<string>("Province")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("SecurityStamp")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("TwoFactorEnabled")
						.HasColumnType("bit");

					b.Property<string>("UserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.HasKey("Id");

					b.HasIndex("NormalizedEmail")
						.HasDatabaseName("EmailIndex");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex")
						.HasFilter("[NormalizedUserName] IS NOT NULL");

					b.ToTable("AspNetUsers", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("RoleId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("UserId", "RoleId");

					b.HasIndex("RoleId");

					b.ToTable("AspNetUserRoles", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("RoleId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RoleId");

					b.ToTable("AspNetRoleClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderKey")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderDisplayName")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("LoginProvider", "ProviderKey");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserLogins", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Value")
						.HasColumnType("nvarchar(max)");

					b.HasKey("UserId", "LoginProvider", "Name");

					b.ToTable("AspNetUserTokens", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", "Role")
						.WithMany("UserRoles")
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("UserRoles")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Role");

					b.Navigation("User");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Claims")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Logins")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Tokens")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Navigation("UserRoles");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Navigation("Claims");

					b.Navigation("Logins");

					b.Navigation("Tokens");

					b.Navigation("UserRoles");
				});
#pragma warning restore 612, 618
		}
	}
}
