// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bizomet.Data.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20220214052815_2022.00.00.06")]
	partial class _2022000006
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.1")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedName")
						.IsUnique()
						.HasDatabaseName("RoleNameIndex")
						.HasFilter("[NormalizedName] IS NOT NULL");

					b.ToTable("AspNetRoles", (string) null);

					b.HasData(
						new
						{
							Id = "8742075e-7145-4bd7-8215-814467809dc2",
							ConcurrencyStamp = "5c24f4c4-6cb7-4c4e-9c51-ed402454f3f7",
							Name = "Administrator",
							NormalizedName = "ADMINISTRATOR"
						},
						new
						{
							Id = "69571a28-cb0d-4fe6-8176-3bffad6c1510",
							ConcurrencyStamp = "0d45966a-3b4c-4b3a-91d1-59a531c98e76",
							Name = "Talent",
							NormalizedName = "TALENT"
						},
						new
						{
							Id = "347ac56d-9576-4f4a-81be-674b4a3a9d0b",
							ConcurrencyStamp = "acfe6006-d571-4d9b-8813-45a0d882abf6",
							Name = "Lifter",
							NormalizedName = "LIFTER"
						},
						new
						{
							Id = "7bd1c590-9eed-44e9-a60c-6e7de0db8f01",
							ConcurrencyStamp = "ddecc949-a921-4c52-84cd-032ffb813cfc",
							Name = "MediaAssistant",
							NormalizedName = "MEDIAASSISTANT"
						},
						new
						{
							Id = "7e6619f8-b336-4f3e-826a-5ce96cef872d",
							ConcurrencyStamp = "42bd4334-2f55-4f49-8e46-27bc20a88a55",
							Name = "Promoter",
							NormalizedName = "PROMOTER"
						},
						new
						{
							Id = "8832961e-a631-445b-9d86-b93f9b4c767b",
							ConcurrencyStamp = "45fbf453-4c26-4d84-8e77-86c0c5444795",
							Name = "Producer",
							NormalizedName = "PRODUCER"
						});
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<int>("AccessFailedCount")
						.HasColumnType("int");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Email")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<bool>("EmailConfirmed")
						.HasColumnType("bit");

					b.Property<bool>("LockoutEnabled")
						.HasColumnType("bit");

					b.Property<DateTimeOffset?>("LockoutEnd")
						.HasColumnType("datetimeoffset");

					b.Property<string>("NormalizedEmail")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("PasswordHash")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PhoneNumber")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<bool>("PhoneNumberConfirmed")
						.HasColumnType("bit");

					b.Property<string>("RefreshToken")
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime?>("RefreshTokenExpiryTime")
						.HasColumnType("datetime2");

					b.Property<string>("SecurityStamp")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("TwoFactorEnabled")
						.HasColumnType("bit");

					b.Property<string>("UserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.HasKey("Id");

					b.HasIndex("NormalizedEmail")
						.HasDatabaseName("EmailIndex");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex")
						.HasFilter("[NormalizedUserName] IS NOT NULL");

					b.ToTable("AspNetUsers", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("RoleId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("UserId", "RoleId");

					b.HasIndex("RoleId");

					b.ToTable("AspNetUserRoles", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserProfile", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AddressLine1")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("AddressLine2")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("City")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Country")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LocationCity")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("LocationCountry")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("LocationState")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("NameTitle")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<string>("PhoneNumberBusiness")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberCell")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberFax")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberHome")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Picture")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("StateProvince")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ZipPostal")
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.HasKey("Id");

					b.HasIndex("UserId")
						.IsUnique();

					b.ToTable("UserProfile");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("RoleId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RoleId");

					b.ToTable("AspNetRoleClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderKey")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderDisplayName")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("LoginProvider", "ProviderKey");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserLogins", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Value")
						.HasColumnType("nvarchar(max)");

					b.HasKey("UserId", "LoginProvider", "Name");

					b.ToTable("AspNetUserTokens", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", "Role")
						.WithMany("UserRoles")
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("UserRoles")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Role");

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserProfile", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithOne("UserProfile")
						.HasForeignKey("Bizomet.Data.Entities.UserProfile", "UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Claims")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Logins")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Tokens")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Navigation("UserRoles");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Navigation("Claims");

					b.Navigation("Logins");

					b.Navigation("Tokens");

					b.Navigation("UserProfile")
						.IsRequired();

					b.Navigation("UserRoles");
				});
#pragma warning restore 612, 618
		}
	}
}
