// <auto-generated />
using System;
using Bizomet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bizomet.Data.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20220121004348_2022.00.00.02")]
	partial class _2022000002
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.1")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedName")
						.IsUnique()
						.HasDatabaseName("RoleNameIndex")
						.HasFilter("[NormalizedName] IS NOT NULL");

					b.ToTable("AspNetRoles", (string) null);

					b.HasData(
						new
						{
							Id = "1d60ea4a-1d46-4357-8618-a552ea479f53",
							ConcurrencyStamp = "9dae23ba-d196-4897-bdea-54f011e7f46d",
							Name = "Administrator",
							NormalizedName = "ADMINISTRATOR"
						},
						new
						{
							Id = "f4d28fca-c2ff-47ee-b635-e7c3f28e6793",
							ConcurrencyStamp = "8de40d62-5f19-4b06-bede-483bc96f1bf7",
							Name = "Talent",
							NormalizedName = "TALENT"
						},
						new
						{
							Id = "2947e0e7-9d5e-42ef-be12-f1291b942ffc",
							ConcurrencyStamp = "5cec362b-898f-4a35-affa-0c5c4a0feedd",
							Name = "Lifter",
							NormalizedName = "LIFTER"
						},
						new
						{
							Id = "b16b277d-9131-4b52-8e8f-27826383d47e",
							ConcurrencyStamp = "a3342867-d3c6-4426-81ea-c3319517768e",
							Name = "MediaAssistant",
							NormalizedName = "MEDIAASSISTANT"
						},
						new
						{
							Id = "b9cd834c-2b02-453a-8bfe-6587958b1990",
							ConcurrencyStamp = "1162684e-dc37-4505-b8c0-ef1ddf426a11",
							Name = "Promoter",
							NormalizedName = "PROMOTER"
						},
						new
						{
							Id = "42c82834-4d88-42c1-a195-de2f68c8eca0",
							ConcurrencyStamp = "92af27f0-ce98-44f7-8c82-7da17638e0b9",
							Name = "Producer",
							NormalizedName = "PRODUCER"
						});
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<int>("AccessFailedCount")
						.HasColumnType("int");

					b.Property<string>("AddressLine1")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("AddressLine2")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("City")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Country")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Email")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<bool>("EmailConfirmed")
						.HasColumnType("bit");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<bool>("LockoutEnabled")
						.HasColumnType("bit");

					b.Property<DateTimeOffset?>("LockoutEnd")
						.HasColumnType("datetimeoffset");

					b.Property<string>("NameTitle")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<string>("NormalizedEmail")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("PasswordHash")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PhoneNumber")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberBusiness")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberCell")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<bool>("PhoneNumberConfirmed")
						.HasColumnType("bit");

					b.Property<string>("PhoneNumberFax")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberHome")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PostalCode")
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<string>("Province")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("SecurityStamp")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("TwoFactorEnabled")
						.HasColumnType("bit");

					b.Property<string>("UserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.HasKey("Id");

					b.HasIndex("NormalizedEmail")
						.HasDatabaseName("EmailIndex");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex")
						.HasFilter("[NormalizedUserName] IS NOT NULL");

					b.ToTable("AspNetUsers", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("RoleId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("UserId", "RoleId");

					b.HasIndex("RoleId");

					b.ToTable("AspNetUserRoles", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("RoleId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RoleId");

					b.ToTable("AspNetRoleClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderKey")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderDisplayName")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("LoginProvider", "ProviderKey");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserLogins", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Value")
						.HasColumnType("nvarchar(max)");

					b.HasKey("UserId", "LoginProvider", "Name");

					b.ToTable("AspNetUserTokens", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", "Role")
						.WithMany("UserRoles")
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("UserRoles")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Role");

					b.Navigation("User");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Claims")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Logins")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Tokens")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Navigation("UserRoles");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Navigation("Claims");

					b.Navigation("Logins");

					b.Navigation("Tokens");

					b.Navigation("UserRoles");
				});
#pragma warning restore 612, 618
		}
	}
}
