// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bizomet.Data.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20220324023628_2022.00.00.16")]
	partial class _2022000016
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.2")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedName")
						.IsUnique()
						.HasDatabaseName("RoleNameIndex")
						.HasFilter("[NormalizedName] IS NOT NULL");

					b.ToTable("AspNetRoles", (string) null);

					b.HasData(
						new
						{
							Id = "8742075e-7145-4bd7-8215-814467809dc2",
							ConcurrencyStamp = "32e3175a-e279-4224-b4af-89d3331dbfee",
							Name = "Administrator",
							NormalizedName = "ADMINISTRATOR"
						},
						new
						{
							Id = "69571a28-cb0d-4fe6-8176-3bffad6c1510",
							ConcurrencyStamp = "4a9bab80-2724-4355-8c95-1786455298b9",
							Name = "Talent",
							NormalizedName = "TALENT"
						},
						new
						{
							Id = "347ac56d-9576-4f4a-81be-674b4a3a9d0b",
							ConcurrencyStamp = "6634449e-d4b1-4ab8-9326-d6d84298ee96",
							Name = "Uplifter",
							NormalizedName = "UPLIFTER"
						},
						new
						{
							Id = "7bd1c590-9eed-44e9-a60c-6e7de0db8f01",
							ConcurrencyStamp = "571bfac0-4bfb-4382-b75c-0147536044d4",
							Name = "MediaAssistant",
							NormalizedName = "MEDIAASSISTANT"
						},
						new
						{
							Id = "7e6619f8-b336-4f3e-826a-5ce96cef872d",
							ConcurrencyStamp = "a33e20c9-787c-4e25-9a50-b61b3184011d",
							Name = "Promoter",
							NormalizedName = "PROMOTER"
						},
						new
						{
							Id = "8832961e-a631-445b-9d86-b93f9b4c767b",
							ConcurrencyStamp = "5c6495ed-2f44-40c9-94a5-e2bd8a68d446",
							Name = "Producer",
							NormalizedName = "PRODUCER"
						});
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<int>("AccessFailedCount")
						.HasColumnType("int");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Email")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<bool>("EmailConfirmed")
						.HasColumnType("bit");

					b.Property<bool>("LockoutEnabled")
						.HasColumnType("bit");

					b.Property<DateTimeOffset?>("LockoutEnd")
						.HasColumnType("datetimeoffset");

					b.Property<string>("NormalizedEmail")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("PasswordHash")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PhoneNumber")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<bool>("PhoneNumberConfirmed")
						.HasColumnType("bit");

					b.Property<string>("SecurityStamp")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("TwoFactorEnabled")
						.HasColumnType("bit");

					b.Property<string>("UserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.HasKey("Id");

					b.HasIndex("NormalizedEmail")
						.HasDatabaseName("EmailIndex");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex")
						.HasFilter("[NormalizedUserName] IS NOT NULL");

					b.ToTable("AspNetUsers", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("RoleId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("UserId", "RoleId");

					b.HasIndex("RoleId");

					b.ToTable("AspNetUserRoles", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ContactUsRequest", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AddressLine1")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("AddressLine2")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("City")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Country")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Description")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Email")
						.IsRequired()
						.HasMaxLength(150)
						.HasColumnType("nvarchar(150)");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("PhoneNumber")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("Reason")
						.HasColumnType("int");

					b.Property<string>("StateProvince")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("UserId")
						.HasMaxLength(450)
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId")
						.HasDatabaseName("UserContactUsRequestsIndex");

					b.ToTable("ContactUsRequest");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Inquiry", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime>("RequestDate")
						.HasColumnType("datetime2");

					b.Property<string>("Title")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RequestDate");

					b.HasIndex("UserId");

					b.ToTable("Inquiry");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Project", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime>("DueDate")
						.HasColumnType("datetime2");

					b.Property<int>("InterviewCondition")
						.HasColumnType("int");

					b.Property<string>("InterviewConditionComment")
						.HasMaxLength(4000)
						.HasColumnType("nvarchar(4000)");

					b.Property<int>("InterviewResult")
						.HasColumnType("int");

					b.Property<string>("InterviewResultComment")
						.HasMaxLength(4000)
						.HasColumnType("nvarchar(4000)");

					b.Property<string>("Location")
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<int>("MediaAssistantFinancialService")
						.HasColumnType("int");

					b.Property<int>("ProducerFinancialService")
						.HasColumnType("int");

					b.Property<int>("PromoterFinancialService")
						.HasColumnType("int");

					b.Property<bool>("RemoteLocation")
						.HasColumnType("bit");

					b.Property<DateTime>("RequestDate")
						.HasColumnType("datetime2");

					b.Property<string>("Title")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.Property<bool>("WishContactedByMediaAssistant")
						.HasColumnType("bit");

					b.Property<bool>("WishContactedByProducer")
						.HasColumnType("bit");

					b.Property<bool>("WishContactedByPromoter")
						.HasColumnType("bit");

					b.HasKey("Id");

					b.HasIndex("RequestDate");

					b.HasIndex("UserId");

					b.ToTable("Project");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.RefreshToken", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<DateTime>("Created")
						.HasColumnType("datetime2");

					b.Property<string>("CreatedByIp")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime>("Expires")
						.HasColumnType("datetime2");

					b.Property<string>("ReplacedByToken")
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime?>("Revoked")
						.HasColumnType("datetime2");

					b.Property<string>("RevokedByIp")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Token")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("RefreshToken");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserPortfolio", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Link")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("Order")
						.HasColumnType("int");

					b.Property<string>("Title")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("UserPortfolio");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserProfile", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AddressLine1")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("AddressLine2")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("City")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Country")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Description")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LocationCity")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("LocationCountry")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("LocationState")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("NameTitle")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<string>("PhoneNumberBusiness")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberCell")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberFax")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberHome")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Picture")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("StateProvince")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Tags")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ZipPostal")
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.HasKey("Id");

					b.HasIndex("UserId")
						.IsUnique();

					b.ToTable("UserProfile");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("RoleId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RoleId");

					b.ToTable("AspNetRoleClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderKey")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderDisplayName")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("LoginProvider", "ProviderKey");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserLogins", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Value")
						.HasColumnType("nvarchar(max)");

					b.HasKey("UserId", "LoginProvider", "Name");

					b.ToTable("AspNetUserTokens", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", "Role")
						.WithMany("UserRoles")
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("UserRoles")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Role");

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Inquiry", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("Inquiries")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Project", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("Projects")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.RefreshToken", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("RefreshTokens")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserPortfolio", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("UserPortfolio")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserProfile", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithOne("UserProfile")
						.HasForeignKey("Bizomet.Data.Entities.UserProfile", "UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Claims")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Logins")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Tokens")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Navigation("UserRoles");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Navigation("Claims");

					b.Navigation("Inquiries");

					b.Navigation("Logins");

					b.Navigation("Projects");

					b.Navigation("RefreshTokens");

					b.Navigation("Tokens");

					b.Navigation("UserPortfolio");

					b.Navigation("UserProfile")
						.IsRequired();

					b.Navigation("UserRoles");
				});
#pragma warning restore 612, 618
		}
	}
}
