// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bizomet.Data.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20220403235527_2022.00.00.20")]
	partial class _2022000020
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.2")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedName")
						.IsUnique()
						.HasDatabaseName("RoleNameIndex")
						.HasFilter("[NormalizedName] IS NOT NULL");

					b.ToTable("AspNetRoles", (string) null);

					b.HasData(
						new
						{
							Id = "8742075e-7145-4bd7-8215-814467809dc2",
							ConcurrencyStamp = "4e6a2506-1824-40b3-ad3b-7c93a7a59015",
							Name = "Administrator",
							NormalizedName = "ADMINISTRATOR"
						},
						new
						{
							Id = "69571a28-cb0d-4fe6-8176-3bffad6c1510",
							ConcurrencyStamp = "8893ec2a-e64d-4b10-9a2e-b635d2187177",
							Name = "Talent",
							NormalizedName = "TALENT"
						},
						new
						{
							Id = "347ac56d-9576-4f4a-81be-674b4a3a9d0b",
							ConcurrencyStamp = "cba30c95-e45f-4fd5-81e8-b15300cebfe8",
							Name = "Uplifter",
							NormalizedName = "UPLIFTER"
						},
						new
						{
							Id = "7bd1c590-9eed-44e9-a60c-6e7de0db8f01",
							ConcurrencyStamp = "b4a481c5-274d-4bfe-8fa6-c99c30664c9a",
							Name = "MediaAssistant",
							NormalizedName = "MEDIAASSISTANT"
						},
						new
						{
							Id = "7e6619f8-b336-4f3e-826a-5ce96cef872d",
							ConcurrencyStamp = "3054a8e2-2eec-4ab0-bd50-7045226a4a81",
							Name = "Promoter",
							NormalizedName = "PROMOTER"
						},
						new
						{
							Id = "8832961e-a631-445b-9d86-b93f9b4c767b",
							ConcurrencyStamp = "d295a5a5-0046-484c-9852-34c7b646d343",
							Name = "Producer",
							NormalizedName = "PRODUCER"
						});
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<int>("AccessFailedCount")
						.HasColumnType("int");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Email")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<bool>("EmailConfirmed")
						.HasColumnType("bit");

					b.Property<bool>("LockoutEnabled")
						.HasColumnType("bit");

					b.Property<DateTimeOffset?>("LockoutEnd")
						.HasColumnType("datetimeoffset");

					b.Property<string>("NormalizedEmail")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("PasswordHash")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PhoneNumber")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<bool>("PhoneNumberConfirmed")
						.HasColumnType("bit");

					b.Property<string>("SecurityStamp")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("TwoFactorEnabled")
						.HasColumnType("bit");

					b.Property<string>("UserName")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.HasKey("Id");

					b.HasIndex("NormalizedEmail")
						.HasDatabaseName("EmailIndex");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex")
						.HasFilter("[NormalizedUserName] IS NOT NULL");

					b.ToTable("AspNetUsers", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("RoleId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("UserId", "RoleId");

					b.HasIndex("RoleId");

					b.ToTable("AspNetUserRoles", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.City", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("CountryCode")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<int>("CountryId")
						.HasColumnType("int");

					b.Property<decimal?>("Latitude")
						.HasPrecision(11, 8)
						.HasColumnType("decimal(11,8)");

					b.Property<decimal?>("Longitude")
						.HasPrecision(11, 8)
						.HasColumnType("decimal(11,8)");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("StateCode")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<int>("StateId")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("Name")
						.HasDatabaseName("CityIndex");

					b.HasIndex("StateId");

					b.HasIndex("StateCode", "Name")
						.HasDatabaseName("StateCityIndex");

					b.HasIndex("CountryCode", "StateCode", "Name")
						.HasDatabaseName("CountryStateCityIndex");

					b.HasIndex("CountryId", "StateId", "Id")
						.IsUnique()
						.HasDatabaseName("CountryStateCityByIdIndex");

					b.ToTable("Location.Cities", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ContactUsRequest", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AddressLine1")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("AddressLine2")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("City")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Country")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Description")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Email")
						.IsRequired()
						.HasMaxLength(150)
						.HasColumnType("nvarchar(150)");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("PhoneNumber")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("Reason")
						.HasColumnType("int");

					b.Property<string>("StateProvince")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("UserId")
						.HasMaxLength(450)
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId")
						.HasDatabaseName("UserContactUsRequestsIndex");

					b.ToTable("ContactUsRequest");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Country", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("Capital")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("Currency")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("CurrencyName")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("CurrencySymbol")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("ISO2")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<string>("ISO3")
						.IsRequired()
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<decimal?>("Latitude")
						.HasPrecision(11, 8)
						.HasColumnType("decimal(11,8)");

					b.Property<decimal?>("Longitude")
						.HasPrecision(11, 8)
						.HasColumnType("decimal(11,8)");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<string>("NumericCode")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<string>("PhoneCode")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("Region")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("SubRegion")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("TLD")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.HasKey("Id");

					b.HasIndex("Name")
						.HasDatabaseName("CountryIndex");

					b.ToTable("Location.Countries", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Inquiry", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime>("RequestDate")
						.HasColumnType("datetime2");

					b.Property<string>("Title")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RequestDate");

					b.HasIndex("UserId");

					b.ToTable("Inquiry");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Project", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime>("DueDate")
						.HasColumnType("datetime2");

					b.Property<int>("InterviewCondition")
						.HasColumnType("int");

					b.Property<string>("InterviewConditionComment")
						.HasMaxLength(4000)
						.HasColumnType("nvarchar(4000)");

					b.Property<int>("InterviewResult")
						.HasColumnType("int");

					b.Property<string>("InterviewResultComment")
						.HasMaxLength(4000)
						.HasColumnType("nvarchar(4000)");

					b.Property<string>("Location")
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<int>("MediaAssistantFinancialService")
						.HasColumnType("int");

					b.Property<int>("ProducerFinancialService")
						.HasColumnType("int");

					b.Property<int>("PromoterFinancialService")
						.HasColumnType("int");

					b.Property<bool>("RemoteLocation")
						.HasColumnType("bit");

					b.Property<DateTime>("RequestDate")
						.HasColumnType("datetime2");

					b.Property<string>("Title")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.Property<bool>("WishContactedByMediaAssistant")
						.HasColumnType("bit");

					b.Property<bool>("WishContactedByProducer")
						.HasColumnType("bit");

					b.Property<bool>("WishContactedByPromoter")
						.HasColumnType("bit");

					b.HasKey("Id");

					b.HasIndex("RequestDate");

					b.HasIndex("UserId");

					b.ToTable("Project");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ProjectAttachment", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<byte[]>("BinaryContent")
						.IsRequired()
						.HasColumnType("varbinary(max)");

					b.Property<string>("FileName")
						.IsRequired()
						.HasMaxLength(2000)
						.HasColumnType("nvarchar(2000)");

					b.Property<string>("FileType")
						.IsRequired()
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<Guid>("ProjectId")
						.HasColumnType("uniqueidentifier");

					b.Property<long>("Size")
						.HasColumnType("bigint");

					b.Property<string>("Thumbnail")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Title")
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.HasKey("Id");

					b.HasIndex("ProjectId");

					b.ToTable("ProjectAttachment");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.RefreshToken", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<DateTime>("Created")
						.HasColumnType("datetime2");

					b.Property<string>("CreatedByIp")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime>("Expires")
						.HasColumnType("datetime2");

					b.Property<string>("ReplacedByToken")
						.HasColumnType("nvarchar(max)");

					b.Property<DateTime?>("Revoked")
						.HasColumnType("datetime2");

					b.Property<string>("RevokedByIp")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Token")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("RefreshToken");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.State", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("CountryCode")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<int>("CountryId")
						.HasColumnType("int");

					b.Property<string>("FipsCode")
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("ISO2")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<decimal?>("Latitude")
						.HasPrecision(11, 8)
						.HasColumnType("decimal(11,8)");

					b.Property<decimal?>("Longitude")
						.HasPrecision(11, 8)
						.HasColumnType("decimal(11,8)");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(510)
						.HasColumnType("nvarchar(510)");

					b.Property<string>("Type")
						.HasMaxLength(400)
						.HasColumnType("nvarchar(400)");

					b.HasKey("Id");

					b.HasIndex("CountryId");

					b.HasIndex("Name")
						.HasDatabaseName("StateIndex");

					b.HasIndex("CountryCode", "Name")
						.HasDatabaseName("CountryStateIndex");

					b.ToTable("Location.States", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserPortfolio", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Link")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("Order")
						.HasColumnType("int");

					b.Property<string>("Title")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("UserPortfolio");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserProfile", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AddressLine1")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("AddressLine2")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("City")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Country")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Description")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("nvarchar(500)");

					b.Property<string>("LocationCity")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("LocationCountry")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("LocationState")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("NameTitle")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<string>("PhoneNumberBusiness")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberCell")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberFax")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PhoneNumberHome")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Picture")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("StateProvince")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("Tags")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ZipPostal")
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.HasKey("Id");

					b.HasIndex("UserId")
						.IsUnique();

					b.ToTable("UserProfile");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("RoleId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RoleId");

					b.ToTable("AspNetRoleClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderKey")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderDisplayName")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("LoginProvider", "ProviderKey");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserLogins", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Value")
						.HasColumnType("nvarchar(max)");

					b.HasKey("UserId", "LoginProvider", "Name");

					b.ToTable("AspNetUserTokens", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUserRole", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", "Role")
						.WithMany("UserRoles")
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("UserRoles")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Role");

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.City", b =>
				{
					b.HasOne("Bizomet.Data.Entities.Country", "Country")
						.WithMany("Cities")
						.HasForeignKey("CountryId")
						.OnDelete(DeleteBehavior.NoAction)
						.IsRequired();

					b.HasOne("Bizomet.Data.Entities.State", "State")
						.WithMany("Cities")
						.HasForeignKey("StateId")
						.OnDelete(DeleteBehavior.NoAction)
						.IsRequired();

					b.Navigation("Country");

					b.Navigation("State");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Inquiry", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("Inquiries")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Project", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("Projects")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ProjectAttachment", b =>
				{
					b.HasOne("Bizomet.Data.Entities.Project", "Project")
						.WithMany("ProjectAttachments")
						.HasForeignKey("ProjectId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Project");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.RefreshToken", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("RefreshTokens")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.State", b =>
				{
					b.HasOne("Bizomet.Data.Entities.Country", "Country")
						.WithMany("States")
						.HasForeignKey("CountryId")
						.OnDelete(DeleteBehavior.NoAction)
						.IsRequired();

					b.Navigation("Country");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserPortfolio", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithMany("UserPortfolio")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.UserProfile", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", "User")
						.WithOne("UserProfile")
						.HasForeignKey("Bizomet.Data.Entities.UserProfile", "UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Claims")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Logins")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.HasOne("Bizomet.Data.Entities.ApplicationUser", null)
						.WithMany("Tokens")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationRole", b =>
				{
					b.Navigation("UserRoles");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.ApplicationUser", b =>
				{
					b.Navigation("Claims");

					b.Navigation("Inquiries");

					b.Navigation("Logins");

					b.Navigation("Projects");

					b.Navigation("RefreshTokens");

					b.Navigation("Tokens");

					b.Navigation("UserPortfolio");

					b.Navigation("UserProfile")
						.IsRequired();

					b.Navigation("UserRoles");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Country", b =>
				{
					b.Navigation("Cities");

					b.Navigation("States");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.Project", b =>
				{
					b.Navigation("ProjectAttachments");
				});

			modelBuilder.Entity("Bizomet.Data.Entities.State", b =>
				{
					b.Navigation("Cities");
				});
#pragma warning restore 612, 618
		}
	}
}
