// <auto-generated />
using System;
using Bizomet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bizomet.Data.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	partial class ApplicationDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.1")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("Bizomet.Data.Models.ApplicationUser", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<int>("AccessFailedCount")
						.HasColumnType("int");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Email")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<bool>("EmailConfirmed")
						.HasColumnType("bit");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("LockoutEnabled")
						.HasColumnType("bit");

					b.Property<DateTimeOffset?>("LockoutEnd")
						.HasColumnType("datetimeoffset");

					b.Property<string>("NormalizedEmail")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("PasswordHash")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PhoneNumber")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("PhoneNumberConfirmed")
						.HasColumnType("bit");

					b.Property<string>("SecurityStamp")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("TwoFactorEnabled")
						.HasColumnType("bit");

					b.Property<string>("UserName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedEmail")
						.HasDatabaseName("EmailIndex");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex")
						.HasFilter("[NormalizedUserName] IS NOT NULL");

					b.ToTable("AspNetUsers", (string) null);
				});

			modelBuilder.Entity("Bizomet.Data.Models.Company", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Address")
						.IsRequired()
						.HasMaxLength(60)
						.HasColumnType("nvarchar(60)");

					b.Property<string>("Country")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(60)
						.HasColumnType("nvarchar(60)");

					b.HasKey("Id");

					b.ToTable("Companies");

					b.HasData(
						new
						{
							Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
							Address = "583 Wall Dr. Gwynn Oak, MD 21207",
							Country = "USA",
							Name = "IT_Solutions Ltd"
						},
						new
						{
							Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
							Address = "312 Forest Avenue, BF 923",
							Country = "USA",
							Name = "Admin_Solutions Ltd"
						});
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedName")
						.IsUnique()
						.HasDatabaseName("RoleNameIndex")
						.HasFilter("[NormalizedName] IS NOT NULL");

					b.ToTable("AspNetRoles", (string) null);

					b.HasData(
						new
						{
							Id = "b8039f27-f4bc-49aa-bed5-bd3c1ba4cff3",
							ConcurrencyStamp = "f5ed3627-8a92-4921-ae65-64fdb0bf1cf9",
							Name = "Administrator",
							NormalizedName = "ADMINISTRATOR"
						},
						new
						{
							Id = "0feb7790-a619-40e2-88b7-ebda1bc53cb9",
							ConcurrencyStamp = "24bdf40d-de50-45f2-b504-0b005d279de8",
							Name = "Talent",
							NormalizedName = "TALENT"
						},
						new
						{
							Id = "53f55fb0-cce4-4d63-901a-49a7defe04f2",
							ConcurrencyStamp = "b1b0acdb-c48d-4806-b9a9-8331f8b25cdc",
							Name = "Lifter",
							NormalizedName = "LIFTER"
						},
						new
						{
							Id = "1a42289f-6b6f-4c1d-ad82-92c0a993122f",
							ConcurrencyStamp = "08d3710a-6d25-4df0-b527-8a4f06223f15",
							Name = "MediaAssistant",
							NormalizedName = "MEDIAASSISTANT"
						},
						new
						{
							Id = "98509d4a-e3bd-4df7-bd68-736584abd1dd",
							ConcurrencyStamp = "48427531-d906-46d9-92b6-20940cce2f3e",
							Name = "Promoter",
							NormalizedName = "PROMOTER"
						});
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("RoleId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RoleId");

					b.ToTable("AspNetRoleClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserClaims", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderKey")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderDisplayName")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("LoginProvider", "ProviderKey");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserLogins", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("RoleId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("UserId", "RoleId");

					b.HasIndex("RoleId");

					b.ToTable("AspNetUserRoles", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Value")
						.HasColumnType("nvarchar(max)");

					b.HasKey("UserId", "LoginProvider", "Name");

					b.ToTable("AspNetUserTokens", (string) null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.HasOne("Bizomet.Data.Models.ApplicationUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.HasOne("Bizomet.Data.Models.ApplicationUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
				{
					b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("Bizomet.Data.Models.ApplicationUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.HasOne("Bizomet.Data.Models.ApplicationUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});
#pragma warning restore 612, 618
		}
	}
}
